### ISSUE TITLE
Why go-guerrilla having limit  30kb of email data can be a header

### ISSUE THREAD

**Issue by anandhkumar** [phires/go-guerrilla#33]
I am using go-guerrilla in my production environment, sending mail with header more than 30K, but getting 4x parser error.
Why we have limit 30KB of email data can be a header, we don;t have such limit in postfix.
Can we increase this limit?
Here attached my mail data
[email.txt](https://github.com/phires/go-guerrilla/files/15412655/email.txt)

Please help me here to increase email header size from 30KB to 1MB

**Comment by phires** [comment]
Will have a look into it

**Comment by anandhkumar** [comment]
Can you let me know pls by when this enhancement can be released?

**Comment by phires** [comment]
The header parser now should be able to handle about 10MiB.
It will be made configurable in the future or the limit might even be removed - I have to check the implications of that.
