### ISSUE TITLE
Will go-guerrilla support SMTP AUTH

### ISSUE THREAD

**Issue by anandhkumar** [phires/go-guerrilla#45]
I am looking for SMTP AUTH ( PLAIN & LOGIN ) both to be support in go-guerrilla.

Please let me know will go-guerrilla  support? if yes how to implement this?

Also go-guerrilla support 
Message Limits:  A maximum number of messages ("n") will be allowed per connection? if yes how to implement this?

**Comment by phires** [comment]
Hi,

as go-guerrilla at this point is "only" a MDA (Mail Delivery Agent) without transport capability (therefore no relaying of mails) SMTP Authentication is not needed. Mails are accepted and processed.
If at some point transport capabilities are added, we absolutly will need authentication.

Cheers.
