### ISSUE TITLE
Proposition of a new wiki page: how to do manual testing

### ISSUE THREAD

**Issue by guilhem-martin** [phires/go-guerrilla#46]
Hello,

I propose the following new page in the wiki: [https://github.com/guilhem-martin/go-guerrilla-wiki/blob/docs/manual_tests/Manual-testing.md](https://github.com/guilhem-martin/go-guerrilla-wiki/blob/docs/manual_tests/Manual-testing.md)

Let me know if you think this brings value. If it does, let me know if you see anything to improve so that I review it.
Thanks.

**Comment by phires** [comment]
Hi, that looks quite good, could you create a PR for this?

**Comment by guilhem-martin** [comment]
@phires I'm not sure we can create a PR for wiki in GitHub?

If not, please feel free to copy paste the content in the main repo wiki.

**Comment by phires** [comment]
Hi, if added the page to the wiki, thank you a lot :)
