### ISSUE TITLE
add ability to use certs passed in config

### ISSUE THREAD

**Issue by vtolstov** [phires/go-guerrilla#50]
i need to run guerrilla with pem encoded certs passed as env to docker container. 
If i want to add such ability - where i can start ? Do you accept such change ?

**Comment by phires** [comment]
Hi, thank you for wanting to contribute to the project :)

This is tightly connected to the long-stanting feature regarding "running in Docker", as most parts of the configuration should be doable via environment variables in the future. If you want to start and tackle this issue, the best starting point will be the "config.go". There the configuration JSON file is loaded, so maybe we could create a function to get values from the environment and set them to the respective server. Main issue might be the multiple server feature, so we would need environment variables like "GOGUERRILLA_SERVER_1_PRIVATEKEYFILE" or something like that.
Also, at this point we can only load certs and keys from files, so if you want to pass the PEM encoded certificate directly there needs to be a new setting for this.

**Comment by vtolstov** [comment]
ok, thank you for answers
